FROM alpine

ARG TARGETPLATFORM

COPY entrypoint_latest_autoinstall.sh /entrypoint.sh

RUN case "$TARGETPLATFORM" in \
        linux/arm64 | linux/amd64) \
            apk add --no-cache nftables && \
             rm -vrf /var/log/apk.log ;; \
        *) echo "Unsupported platform: $TARGETPLATFORM" ;; \
    esac

RUN apk add --no-cache netcat-openbsd nano tzdata ca-certificates tini && \
    rm -vrf /var/cache/apk/* && \
    chmod +x /entrypoint.sh

ENTRYPOINT ["tini", "--", "/entrypoint.sh"]